#include <Parsers/tests/gtest_common.h>

#include <Parsers/Kusto/ParserKQLStatement.h>

INSTANTIATE_TEST_SUITE_P(ParserKQLQuery_MakeSeries, ParserKQLTest,
    ::testing::Combine(
        ::testing::Values(std::make_shared<DB::ParserKQLStatement>()),
        ::testing::ValuesIn(std::initializer_list<ParserTestCase>{
        {
            "T |  make-series PriceAvg = avg(Price) default=0 on Purchase from datetime(2016-09-10)  to datetime(2016-09-13) step 1d by Supplier, Fruit",
            "SELECT\n    Supplier,\n    Fruit,\n    zipped.1 AS Purchase,\n    zipped.2 AS PriceAvg\nFROM\n(\n    SELECT\n        toUInt64(min(Purchase_ali)) AS low,\n        toUInt64(max(Purchase_ali)) + 86400 AS high,\n        arraySort(arrayZip(Purchase, PriceAvg)) AS zipped,\n        Supplier,\n        Fruit,\n        arrayConcat(groupArray(PriceAvg_ali) AS ga1, arrayMap(x -> 0, range(0, toUInt32(if((length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1)) < 0, 0, length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1))), 1))) AS PriceAvg,\n        arrayDistinct(arrayConcat(groupArray(toDateTime64(Purchase_ali - 0, 9, 'UTC')), arrayMap(x -> toDateTime64(x - 0, 9, 'UTC'), range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))))) AS Purchase\n    FROM\n    (\n        SELECT\n            Supplier,\n            Fruit,\n            avg(Price) AS PriceAvg_ali,\n            toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))) + (toInt64((toFloat64(toDateTime64(Purchase, 9, 'UTC')) - toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) / 86400) * 86400) AS Purchase_ali\n        FROM T\n        WHERE (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) >= toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) AND (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) < toUInt64(toDateTime64('2016-09-13', 9, 'UTC')))\n        GROUP BY\n            Supplier,\n            Fruit,\n            Purchase_ali\n        ORDER BY Purchase_ali ASC\n    )\n    GROUP BY\n        Supplier,\n        Fruit\n)"
        },
        {
            "T2 | make-series PriceAvg=avg(Price) default=0 on Purchase from 10 to  15 step  1.0  by Supplier, Fruit",
            "SELECT\n    Supplier,\n    Fruit,\n    zipped.1 AS Purchase,\n    zipped.2 AS PriceAvg\nFROM\n(\n    SELECT\n        toUInt64(min(Purchase_ali)) AS low,\n        toUInt64(max(Purchase_ali)) + 1 AS high,\n        arraySort(arrayZip(Purchase, PriceAvg)) AS zipped,\n        Supplier,\n        Fruit,\n        arrayConcat(groupArray(PriceAvg_ali) AS ga1, arrayMap(x -> 0, range(0, toUInt32(if((length(range(toUInt64(10), toUInt64(15), toUInt64(1))) - length(ga1)) < 0, 0, length(range(toUInt64(10), toUInt64(15), toUInt64(1))) - length(ga1))), 1))) AS PriceAvg,\n        arrayDistinct(arrayConcat(groupArray(Purchase_ali), arrayMap(x -> toFloat64(x), range(toUInt64(10), toUInt64(15), toUInt64(1))))) AS Purchase\n    FROM\n    (\n        SELECT\n            Supplier,\n            Fruit,\n            avg(Price) AS PriceAvg_ali,\n            toFloat64(10) + (toInt64((toFloat64(Purchase) - toFloat64(10)) / 1) * 1) AS Purchase_ali\n        FROM T2\n        WHERE (toInt64(toFloat64(Purchase)) >= toUInt64(10)) AND (toInt64(toFloat64(Purchase)) < toUInt64(15))\n        GROUP BY\n            Supplier,\n            Fruit,\n            Purchase_ali\n        ORDER BY Purchase_ali ASC\n    )\n    GROUP BY\n        Supplier,\n        Fruit\n)"
        },
        {
            "T |  make-series PriceAvg = avg(Price) default=0 on Purchase step 1d by Supplier, Fruit",
            "SELECT\n    Supplier,\n    Fruit,\n    zipped.1 AS Purchase,\n    zipped.2 AS PriceAvg\nFROM\n(\n    SELECT\n        toUInt64(min(Purchase_ali)) AS low,\n        toUInt64(max(Purchase_ali)) + 86400 AS high,\n        arraySort(arrayZip(Purchase, PriceAvg)) AS zipped,\n        Supplier,\n        Fruit,\n        arrayConcat(groupArray(PriceAvg_ali) AS ga1, arrayMap(x -> 0, range(0, toUInt32(if((length(range(low, high, toUInt64(86400))) - length(ga1)) < 0, 0, length(range(low, high, toUInt64(86400))) - length(ga1))), 1))) AS PriceAvg,\n        arrayDistinct(arrayConcat(groupArray(toDateTime64(Purchase_ali - 62135596800, 9, 'UTC')), arrayMap(x -> toDateTime64(x - 62135596800, 9, 'UTC'), range(low, high, toUInt64(86400))))) AS Purchase\n    FROM\n    (\n        SELECT\n            Supplier,\n            Fruit,\n            avg(Price) AS PriceAvg_ali,\n            toFloat64(toInt64((toFloat64(toDateTime64(Purchase, 9, 'UTC')) + 62135596800) / 86400) * 86400) AS Purchase_ali\n        FROM T\n        GROUP BY\n            Supplier,\n            Fruit,\n            Purchase_ali\n        ORDER BY Purchase_ali ASC\n    )\n    GROUP BY\n        Supplier,\n        Fruit\n)"
        },
        {
            "T2 | make-series PriceAvg=avg(Price) default=0 on Purchase step  1.0  by Supplier, Fruit",
            "SELECT\n    Supplier,\n    Fruit,\n    zipped.1 AS Purchase,\n    zipped.2 AS PriceAvg\nFROM\n(\n    SELECT\n        toUInt64(min(Purchase_ali)) AS low,\n        toUInt64(max(Purchase_ali)) + 1 AS high,\n        arraySort(arrayZip(Purchase, PriceAvg)) AS zipped,\n        Supplier,\n        Fruit,\n        arrayConcat(groupArray(PriceAvg_ali) AS ga1, arrayMap(x -> 0, range(0, toUInt32(if((length(range(low, high, toUInt64(1))) - length(ga1)) < 0, 0, length(range(low, high, toUInt64(1))) - length(ga1))), 1))) AS PriceAvg,\n        arrayDistinct(arrayConcat(groupArray(Purchase_ali), arrayMap(x -> toFloat64(x), range(low, high, toUInt64(1))))) AS Purchase\n    FROM\n    (\n        SELECT\n            Supplier,\n            Fruit,\n            avg(Price) AS PriceAvg_ali,\n            toFloat64(toInt64((toFloat64(Purchase) + 0) / 1) * 1) AS Purchase_ali\n        FROM T2\n        GROUP BY\n            Supplier,\n            Fruit,\n            Purchase_ali\n        ORDER BY Purchase_ali ASC\n    )\n    GROUP BY\n        Supplier,\n        Fruit\n)"
        },
        {
            "make_series_test_table |  make-series avg(Price+1)  on Purchase from datetime(2016-09-10)  to datetime(2016-09-13) step 1d by Supplier, Fruit | order by Supplier, Fruit;",
            "SELECT *\nFROM\n(\n    SELECT\n        Supplier,\n        Fruit,\n        zipped.1 AS Purchase,\n        zipped.2 AS avg_\n    FROM\n    (\n        SELECT\n            toUInt64(min(Purchase_ali)) AS low,\n            toUInt64(max(Purchase_ali)) + 86400 AS high,\n            arraySort(arrayZip(Purchase, avg_)) AS zipped,\n            Supplier,\n            Fruit,\n            arrayConcat(groupArray(avg__ali) AS ga1, arrayMap(x -> 0, range(0, toUInt32(if((length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1)) < 0, 0, length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1))), 1))) AS avg_,\n            arrayDistinct(arrayConcat(groupArray(toDateTime64(Purchase_ali - 0, 9, 'UTC')), arrayMap(x -> toDateTime64(x - 0, 9, 'UTC'), range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))))) AS Purchase\n        FROM\n        (\n            SELECT\n                Supplier,\n                Fruit,\n                avg(Price + 1) AS avg__ali,\n                toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))) + (toInt64((toFloat64(toDateTime64(Purchase, 9, 'UTC')) - toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) / 86400) * 86400) AS Purchase_ali\n            FROM make_series_test_table\n            WHERE (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) >= toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) AND (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) < toUInt64(toDateTime64('2016-09-13', 9, 'UTC')))\n            GROUP BY\n                Supplier,\n                Fruit,\n                Purchase_ali\n            ORDER BY Purchase_ali ASC\n        )\n        GROUP BY\n            Supplier,\n            Fruit\n    )\n)\nORDER BY\n    Supplier DESC NULLS LAST,\n    Fruit DESC NULLS LAST"
        },
        {
            "make_series_test_table |  make-series dcount(Price+1)  on Purchase from datetime(2016-09-10)  to datetime(2016-09-13) step 1d by Supplier, Fruit | order by Supplier, Fruit;",
            "SELECT *\nFROM\n(\n    SELECT\n        Supplier,\n        Fruit,\n        zipped.1 AS Purchase,\n        zipped.2 AS dcount_\n    FROM\n    (\n        SELECT\n            toUInt64(min(Purchase_ali)) AS low,\n            toUInt64(max(Purchase_ali)) + 86400 AS high,\n            arraySort(arrayZip(Purchase, dcount_)) AS zipped,\n            Supplier,\n            Fruit,\n            arrayConcat(groupArray(dcount__ali) AS ga1, arrayMap(x -> 0, range(0, toUInt32(if((length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1)) < 0, 0, length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1))), 1))) AS dcount_,\n            arrayDistinct(arrayConcat(groupArray(toDateTime64(Purchase_ali - 0, 9, 'UTC')), arrayMap(x -> toDateTime64(x - 0, 9, 'UTC'), range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))))) AS Purchase\n        FROM\n        (\n            SELECT\n                Supplier,\n                Fruit,\n                uniqCombined64(14)(Price + 1) AS dcount__ali,\n                toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))) + (toInt64((toFloat64(toDateTime64(Purchase, 9, 'UTC')) - toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) / 86400) * 86400) AS Purchase_ali\n            FROM make_series_test_table\n            WHERE (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) >= toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) AND (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) < toUInt64(toDateTime64('2016-09-13', 9, 'UTC')))\n            GROUP BY\n                Supplier,\n                Fruit,\n                Purchase_ali\n            ORDER BY Purchase_ali ASC\n        )\n        GROUP BY\n            Supplier,\n            Fruit\n    )\n)\nORDER BY\n    Supplier DESC NULLS LAST,\n    Fruit DESC NULLS LAST"
        },
        {
            "make_series_test_table |  make-series avg(Price+1)+1  on Purchase from datetime(2016-09-10)  to datetime(2016-09-13) step 1d by Supplier, Fruit | order by Supplier, Fruit",
            "SELECT *\nFROM\n(\n    SELECT\n        Supplier,\n        Fruit,\n        zipped.1 AS Purchase,\n        zipped.2 AS avg_\n    FROM\n    (\n        SELECT\n            toUInt64(min(Purchase_ali)) AS low,\n            toUInt64(max(Purchase_ali)) + 86400 AS high,\n            arraySort(arrayZip(Purchase, avg_)) AS zipped,\n            Supplier,\n            Fruit,\n            arrayConcat(groupArray(avg__ali) AS ga1, arrayMap(x -> 0, range(0, toUInt32(if((length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1)) < 0, 0, length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1))), 1))) AS avg_,\n            arrayDistinct(arrayConcat(groupArray(toDateTime64(Purchase_ali - 0, 9, 'UTC')), arrayMap(x -> toDateTime64(x - 0, 9, 'UTC'), range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))))) AS Purchase\n        FROM\n        (\n            SELECT\n                Supplier,\n                Fruit,\n                avg(Price + 1) + 1 AS avg__ali,\n                toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))) + (toInt64((toFloat64(toDateTime64(Purchase, 9, 'UTC')) - toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) / 86400) * 86400) AS Purchase_ali\n            FROM make_series_test_table\n            WHERE (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) >= toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) AND (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) < toUInt64(toDateTime64('2016-09-13', 9, 'UTC')))\n            GROUP BY\n                Supplier,\n                Fruit,\n                Purchase_ali\n            ORDER BY Purchase_ali ASC\n        )\n        GROUP BY\n            Supplier,\n            Fruit\n    )\n)\nORDER BY\n    Supplier DESC NULLS LAST,\n    Fruit DESC NULLS LAST"
        },
        {
            "make_series_test_table |  make-series ceiling(avg(Price+1)+1) on Purchase from datetime(2016-09-10)  to datetime(2016-09-13) step 1d by Supplier, Fruit | order by Supplier, Fruit",
            "SELECT *\nFROM\n(\n    SELECT\n        Supplier,\n        Fruit,\n        zipped.1 AS Purchase,\n        zipped.2 AS Column1\n    FROM\n    (\n        SELECT\n            toUInt64(min(Purchase_ali)) AS low,\n            toUInt64(max(Purchase_ali)) + 86400 AS high,\n            arraySort(arrayZip(Purchase, Column1)) AS zipped,\n            Supplier,\n            Fruit,\n            arrayConcat(groupArray(Column1_ali) AS ga1, arrayMap(x -> 0, range(0, toUInt32(if((length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1)) < 0, 0, length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1))), 1))) AS Column1,\n            arrayDistinct(arrayConcat(groupArray(toDateTime64(Purchase_ali - 0, 9, 'UTC')), arrayMap(x -> toDateTime64(x - 0, 9, 'UTC'), range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))))) AS Purchase\n        FROM\n        (\n            SELECT\n                Supplier,\n                Fruit,\n                ceil(avg(Price + 1) + 1) AS Column1_ali,\n                toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))) + (toInt64((toFloat64(toDateTime64(Purchase, 9, 'UTC')) - toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) / 86400) * 86400) AS Purchase_ali\n            FROM make_series_test_table\n            WHERE (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) >= toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) AND (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) < toUInt64(toDateTime64('2016-09-13', 9, 'UTC')))\n            GROUP BY\n                Supplier,\n                Fruit,\n                Purchase_ali\n            ORDER BY Purchase_ali ASC\n        )\n        GROUP BY\n            Supplier,\n            Fruit\n    )\n)\nORDER BY\n    Supplier DESC NULLS LAST,\n    Fruit DESC NULLS LAST"
        },
        {
            "make_series_test_table |  make-series ceiling(avg(Price+1)+1) default = strlen('123')+1.5 on Purchase from datetime(2016-09-10)  to datetime(2016-09-13) step 1d by Supplier, Fruit | order by Supplier, Fruit;",
            "SELECT *\nFROM\n(\n    SELECT\n        Supplier,\n        Fruit,\n        zipped.1 AS Purchase,\n        zipped.2 AS Column1\n    FROM\n    (\n        SELECT\n            toUInt64(min(Purchase_ali)) AS low,\n            toUInt64(max(Purchase_ali)) + 86400 AS high,\n            arraySort(arrayZip(Purchase, Column1)) AS zipped,\n            Supplier,\n            Fruit,\n            arrayConcat(groupArray(Column1_ali) AS ga1, arrayMap(x -> (lengthUTF8('123') + 1.5), range(0, toUInt32(if((length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1)) < 0, 0, length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1))), 1))) AS Column1,\n            arrayDistinct(arrayConcat(groupArray(toDateTime64(Purchase_ali - 0, 9, 'UTC')), arrayMap(x -> toDateTime64(x - 0, 9, 'UTC'), range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))))) AS Purchase\n        FROM\n        (\n            SELECT\n                Supplier,\n                Fruit,\n                ceil(avg(Price + 1) + 1) AS Column1_ali,\n                toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))) + (toInt64((toFloat64(toDateTime64(Purchase, 9, 'UTC')) - toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) / 86400) * 86400) AS Purchase_ali\n            FROM make_series_test_table\n            WHERE (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) >= toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) AND (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) < toUInt64(toDateTime64('2016-09-13', 9, 'UTC')))\n            GROUP BY\n                Supplier,\n                Fruit,\n                Purchase_ali\n            ORDER BY Purchase_ali ASC\n        )\n        GROUP BY\n            Supplier,\n            Fruit\n    )\n)\nORDER BY\n    Supplier DESC NULLS LAST,\n    Fruit DESC NULLS LAST"
        },
        {
            "make_series_test_table |  make-series avg(Price) on Purchase from datetime(2016-09-10)+1d  to datetime(2016-09-13)+1d step 1d by Supplier, Fruit | order by Supplier, Fruit",
            "SELECT *\nFROM\n(\n    SELECT\n        Supplier,\n        Fruit,\n        zipped.1 AS Purchase,\n        zipped.2 AS avg_\n    FROM\n    (\n        SELECT\n            toUInt64(min(Purchase_ali)) AS low,\n            toUInt64(max(Purchase_ali)) + 86400 AS high,\n            arraySort(arrayZip(Purchase, avg_)) AS zipped,\n            Supplier,\n            Fruit,\n            arrayConcat(groupArray(avg__ali) AS ga1, arrayMap(x -> 0, range(0, toUInt32(if((length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC') + toIntervalNanosecond(86400000000000))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC') + toIntervalNanosecond(86400000000000)), toUInt64(86400))) - length(ga1)) < 0, 0, length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC') + toIntervalNanosecond(86400000000000))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC') + toIntervalNanosecond(86400000000000)), toUInt64(86400))) - length(ga1))), 1))) AS avg_,\n            arrayDistinct(arrayConcat(groupArray(toDateTime64(Purchase_ali - 0, 9, 'UTC')), arrayMap(x -> toDateTime64(x - 0, 9, 'UTC'), range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC') + toIntervalNanosecond(86400000000000))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC') + toIntervalNanosecond(86400000000000)), toUInt64(86400))))) AS Purchase\n        FROM\n        (\n            SELECT\n                Supplier,\n                Fruit,\n                avg(Price) AS avg__ali,\n                toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC') + toIntervalNanosecond(86400000000000))) + (toInt64((toFloat64(toDateTime64(Purchase, 9, 'UTC')) - toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC') + toIntervalNanosecond(86400000000000)))) / 86400) * 86400) AS Purchase_ali\n            FROM make_series_test_table\n            WHERE (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) >= toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC') + toIntervalNanosecond(86400000000000)))) AND (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) < toUInt64(toDateTime64('2016-09-13', 9, 'UTC') + toIntervalNanosecond(86400000000000)))\n            GROUP BY\n                Supplier,\n                Fruit,\n                Purchase_ali\n            ORDER BY Purchase_ali ASC\n        )\n        GROUP BY\n            Supplier,\n            Fruit\n    )\n)\nORDER BY\n    Supplier DESC NULLS LAST,\n    Fruit DESC NULLS LAST"
        },
        {
            "T |  make-series PriceAvg = avg(Price), PriceMax = sum(Price)  on Purchase from datetime(2016-09-10)  to datetime(2016-09-13) step 1d by Supplier, Fruit",
            "SELECT\n    Supplier,\n    Fruit,\n    zipped.1 AS Purchase,\n    zipped.2 AS PriceAvg,\n    zipped.2 AS PriceMax\nFROM\n(\n    SELECT\n        toUInt64(min(Purchase_ali)) AS low,\n        toUInt64(max(Purchase_ali)) + 86400 AS high,\n        arraySort(arrayZip(Purchase, PriceAvg, PriceMax)) AS zipped,\n        Supplier,\n        Fruit,\n        arrayConcat(groupArray(PriceAvg_ali) AS ga1, arrayMap(x -> 0, range(0, toUInt32(if((length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1)) < 0, 0, length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga1))), 1))) AS PriceAvg,\n        arrayConcat(groupArray(PriceMax_ali) AS ga2, arrayMap(x -> 0, range(0, toUInt32(if((length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga2)) < 0, 0, length(range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))) - length(ga2))), 1))) AS PriceMax,\n        arrayDistinct(arrayConcat(groupArray(toDateTime64(Purchase_ali - 0, 9, 'UTC')), arrayMap(x -> toDateTime64(x - 0, 9, 'UTC'), range(toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))), toUInt64(toDateTime64('2016-09-13', 9, 'UTC')), toUInt64(86400))))) AS Purchase\n    FROM\n    (\n        SELECT\n            Supplier,\n            Fruit,\n            avg(Price) AS PriceAvg_ali,\n            sum(Price) AS PriceMax_ali,\n            toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC'))) + (toInt64((toFloat64(toDateTime64(Purchase, 9, 'UTC')) - toFloat64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) / 86400) * 86400) AS Purchase_ali\n        FROM T\n        WHERE (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) >= toUInt64(date_trunc('second', toDateTime64('2016-09-10', 9, 'UTC')))) AND (toInt64(toFloat64(toDateTime64(Purchase, 9, 'UTC'))) < toUInt64(toDateTime64('2016-09-13', 9, 'UTC')))\n        GROUP BY\n            Supplier,\n            Fruit,\n            Purchase_ali\n        ORDER BY Purchase_ali ASC\n    )\n    GROUP BY\n        Supplier,\n        Fruit\n)"
        }
})));
