name: checkdocker

env:
  # Force the stdout and stderr streams to be unbuffered
  PYTHONUNBUFFERED: 1

on:  # yamllint disable-line rule:truthy
  push:
##########################################################################################
##################################### SMALL CHECKS #######################################
##########################################################################################
jobs:
  DockerServerImages:
    runs-on: [self-hosted, build]
    steps:
      - name: Check value
        run: |
          DOCKER_REPO="${DOCKER_REPO:-docker.io}"
          echo "DOCKER_REPO value: $DOCKER_REPO"



      # - name: Check out repository code
      #   uses: ClickHouse/checkout@v1
      #   with:
      #     clear-repository: true
      #     fetch-depth: 0  # It MUST BE THE SAME for all dependencies and the job itself
      # - name: Check docker clickhouse/clickhouse-server building
      #   run: |
      #     cd "$GITHUB_WORKSPACE/tests/ci"
      #     DOCKER_REPO="${DOCKER_REPO:-docker.io}"
      #     python3 docker_server.py --release-type head --no-push \
      #       --image-repo $DOCKER_REPO/clickhouse/clickhouse-server --image-path docker/server
      #     python3 docker_server.py --release-type head --no-push \
      #       --image-repo $DOCKER_REPO/clickhouse/clickhouse-keeper --image-path docker/keeper
      # - name: Cleanup
      #   if: always()
      #   run: |
      #     docker ps --quiet | xargs --no-run-if-empty docker kill ||:
      #     docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
      #     sudo rm -fr "$TEMP_PATH"