name: UnitTests

env:
  # Force the stdout and stderr streams to be unbuffered
  PYTHONUNBUFFERED: 1

on:  # yamllint disable-line rule:truthy
  # workflow_dispatch:  # Enable manual triggering
  push

jobs:
  PythonUnitTests:
    runs-on: [self-hosted, style-checker, python-unit-test]
    steps:
      - name: Check out repository code
        uses: ClickHouse/checkout@v1
        with:
          clear-repository: true
      - name: Python unit tests
        run: |
          cd "$GITHUB_WORKSPACE/tests/ci"
          python3 -m unittest discover -s . -p '*_test.py'